spring:
  cloud:
    config:
      server:
        git:
          # -- local setup --
          # uri: file:///${user.home}/Desktop/demo
          # -- remote setup --
          uri: https://github.com/senacor/BankingInTheCloud-Tutorials
          # define the folder where the config files are placed within the repo
          searchPaths: config-repo
server:
  port: 8888