server:
  port: 8082
  contextPath: /accounts

spring:
  datasource:
    driver-class-name: 'org.h2.Driver'
    url: 'jdbc:h2:mem:accountingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'root'
    password: 'mysql'
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

# note: this configuration is needed to avoid timeout upon initial request
#   somehow the initial request needs more time and runs in a timeout with the default settings
# https://github.com/Netflix/Hystrix/wiki/configuration#execution.isolation.thread.timeoutInMilliseconds
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
